[package]
name = "vec-set"
version = "2.0.0-rc5"
repository = 'https://github.com/substrate-developer-hub/recipes'
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = "2018"
license = "GPL-3.0-or-later"
description = "A pallet that implements a storage Set on top of a Vec"

[package.metadata.substrate]
categories = [
	"pallet",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc5"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'account-set/std'
]

[dependencies]
parity-scale-codec = { version = "1.3.0", features = ["derive"], default-features = false }
frame-support = { version = '2.0.0-rc5', default-features = false }
frame-system = { version = '2.0.0-rc5', default-features = false }
sp-runtime = { version = '2.0.0-rc5', default-features = false }
sp-std = { version = '2.0.0-rc5', default-features = false }
account-set = { path = '../../traits/account-set', default-features = false }

[dev-dependencies]
sp-core = { version = '2.0.0-rc5', default-features = false }
sp-io = { version = '2.0.0-rc5', default-features = false }
